export {
  createEndpoint,
  createValidatedFetch,
  callEndpoint,
  isValidationResult,
  normalizeValidationError,
  resolveRestRouteUrl,
  toValidationResult,
  type ApiEndpoint,
  type EndpointCallOptions,
  type EndpointRequestValidationResult,
  type EndpointResponseValidationResult,
  type EndpointValidationResult,
  type EndpointValidationTarget,
  type ValidatedFetch,
  type ValidationResult,
  type ValidationError,
  type ValidationLike,
} from './client';
export {
  ApiClientConfigurationError,
  RestConfigurationError,
  RestQueryHookUsageError,
  RestRootResolutionError,
  RestValidationAssertionError,
  WpTypiaContractError,
  WpTypiaValidationAssertionError,
} from './errors.js';
export {
  createHeadersDecoder,
  createParameterDecoder,
  createQueryDecoder,
} from './http';
export {
  defineRestResource,
  defineRestResourceListQuery,
  toRestResourceListRequest,
  type RestResource,
  type RestResourceCreateRequest,
  type RestResourceCreateResponse,
  type RestResourceDefinition,
  type RestResourceDeleteRequest,
  type RestResourceDeleteResponse,
  type RestResourceEndpointSet,
  type RestResourceListQueryBridge,
  type RestResourceListRequest,
  type RestResourceListResponse,
  type RestResourceReadRequest,
  type RestResourceReadResponse,
  type RestResourceUpdateRequest,
  type RestResourceUpdateResponse,
} from './resource.js';
