/**
 * Built-in emitter template bodies grouped away from artifact assembly so
 * authoring stays focused on the emitted TS/TSX/PHP sources themselves.
 */

export {
	BLOCK_METADATA_WRAPPER_TEMPLATE,
	MANIFEST_DEFAULTS_DOCUMENT_WRAPPER_TEMPLATE,
	MANIFEST_DOCUMENT_WRAPPER_TEMPLATE,
	SHARED_HOOKS_TEMPLATE,
} from "./built-in-block-code-templates/shared.js";

export {
	BASIC_EDIT_TEMPLATE,
	BASIC_INDEX_TEMPLATE,
	BASIC_SAVE_TEMPLATE,
	BASIC_VALIDATORS_TEMPLATE,
} from "./built-in-block-code-templates/basic.js";

export {
	INTERACTIVITY_EDIT_TEMPLATE,
	INTERACTIVITY_INDEX_TEMPLATE,
	INTERACTIVITY_SAVE_TEMPLATE,
	INTERACTIVITY_SCRIPT_TEMPLATE,
	INTERACTIVITY_VALIDATORS_TEMPLATE,
} from "./built-in-block-code-templates/interactivity.js";

export {
	PERSISTENCE_EDIT_TEMPLATE,
	PERSISTENCE_INDEX_TEMPLATE,
	PERSISTENCE_INTERACTIVITY_TEMPLATE,
	PERSISTENCE_SAVE_TEMPLATE,
	PERSISTENCE_VALIDATORS_TEMPLATE,
} from "./built-in-block-code-templates/persistence.js";

export {
	QUERY_LOOP_INDEX_TEMPLATE,
} from "./built-in-block-code-templates/query-loop.js";

export {
	COMPOUND_CHILD_EDIT_TEMPLATE,
	COMPOUND_CHILD_INDEX_TEMPLATE,
	COMPOUND_CHILDREN_TEMPLATE,
	COMPOUND_CHILD_SAVE_TEMPLATE,
	COMPOUND_CHILD_VALIDATORS_TEMPLATE,
	COMPOUND_LOCAL_HOOKS_TEMPLATE,
	COMPOUND_PARENT_EDIT_TEMPLATE,
	COMPOUND_PARENT_INDEX_TEMPLATE,
	COMPOUND_PARENT_SAVE_TEMPLATE,
	COMPOUND_PARENT_VALIDATORS_TEMPLATE,
	COMPOUND_PERSISTENCE_PARENT_EDIT_TEMPLATE,
	COMPOUND_PERSISTENCE_PARENT_INTERACTIVITY_TEMPLATE,
	COMPOUND_PERSISTENCE_PARENT_SAVE_TEMPLATE,
	COMPOUND_PERSISTENCE_PARENT_VALIDATORS_TEMPLATE,
} from "./built-in-block-code-templates/compound.js";
