export {
	COMPOUND_CHILDREN_TEMPLATE,
	COMPOUND_LOCAL_HOOKS_TEMPLATE,
	COMPOUND_PARENT_EDIT_TEMPLATE,
	COMPOUND_PARENT_INDEX_TEMPLATE,
	COMPOUND_PARENT_SAVE_TEMPLATE,
	COMPOUND_PARENT_VALIDATORS_TEMPLATE,
} from './compound-parent.js';

export {
	COMPOUND_CHILD_EDIT_TEMPLATE,
	COMPOUND_CHILD_INDEX_TEMPLATE,
	COMPOUND_CHILD_SAVE_TEMPLATE,
	COMPOUND_CHILD_VALIDATORS_TEMPLATE,
} from './compound-child.js';

export {
	COMPOUND_PERSISTENCE_PARENT_EDIT_TEMPLATE,
	COMPOUND_PERSISTENCE_PARENT_INTERACTIVITY_TEMPLATE,
	COMPOUND_PERSISTENCE_PARENT_SAVE_TEMPLATE,
	COMPOUND_PERSISTENCE_PARENT_VALIDATORS_TEMPLATE,
} from './compound-persistence.js';
