import fs from "node:fs/promises";
import path from "node:path";

import { Generator } from "@bunli/generator";

import {
	ADD_OPTION_METADATA,
	buildCommandOptionParser,
	CREATE_OPTION_METADATA,
	GLOBAL_OPTION_METADATA,
	MIGRATE_OPTION_METADATA,
	TEMPLATES_OPTION_METADATA,
} from "../src/command-option-metadata";
import { WP_TYPIA_BUN_REQUIRED_TOP_LEVEL_COMMAND_NAMES } from "../src/command-contract";

const packageRoot = path.resolve(import.meta.dir, "..");
const outputDir = path.join(packageRoot, ".bunli");
const outputFile = path.join(outputDir, "commands.gen.ts");
const binRoutingMetadataFile = path.join(
	packageRoot,
	"bin",
	"routing-metadata.generated.js",
);

function toSortedArray(values: Iterable<string>): string[] {
	return Array.from(new Set(values)).sort((left, right) =>
		left.localeCompare(right),
	);
}

async function writeBinRoutingMetadata() {
	const parser = buildCommandOptionParser(
		ADD_OPTION_METADATA,
		GLOBAL_OPTION_METADATA,
		CREATE_OPTION_METADATA,
		MIGRATE_OPTION_METADATA,
		TEMPLATES_OPTION_METADATA,
	);
	const longValueOptions = toSortedArray(parser.stringOptionNames).map(
		(optionName) => `--${optionName}`,
	);
	const shortValueOptions = toSortedArray(
		Array.from(parser.shortFlagMap.entries())
			.filter(([, option]) => option.type === "string")
			.map(([short]) => `-${short}`),
	);
	const fileContents = `// This file was automatically generated by \`bun run generate\`.
// Do not edit directly.

export const fullRuntimeCommands = Object.freeze(${JSON.stringify(
		WP_TYPIA_BUN_REQUIRED_TOP_LEVEL_COMMAND_NAMES,
		null,
		2,
	)});
export const longValueOptions = Object.freeze(${JSON.stringify(
		longValueOptions,
		null,
		2,
	)});
export const shortValueOptions = Object.freeze(${JSON.stringify(
		shortValueOptions,
		null,
		2,
	)});
`;

	await fs.writeFile(binRoutingMetadataFile, fileContents, "utf8");
}

await fs.mkdir(outputDir, { recursive: true });

const generator = new Generator({
	directory: path.join(packageRoot, "src", "commands"),
	entry: path.join(packageRoot, "src", "cli.ts"),
	generateReport: false,
	outputFile,
});

const result = await generator.run();

if ("error" in result && result.error) {
	console.error(result.error);
	process.exit(1);
}

await writeBinRoutingMetadata();
